-- Auto-generated SQL Script using country-state-city real data for Pakistan

-- Create Provinces Table
CREATE TABLE IF NOT EXISTS public.provinces (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create Cities Table
CREATE TABLE IF NOT EXISTS public.cities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  province_id UUID REFERENCES public.provinces(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_serviceable BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(province_id, name)
);

-- Enable RLS and grant read access to all users
ALTER TABLE public.provinces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read on provinces" ON public.provinces FOR SELECT USING (true);
CREATE POLICY "Allow public read on cities" ON public.cities FOR SELECT USING (true);
GRANT SELECT ON public.provinces TO anon, authenticated;
GRANT SELECT ON public.cities TO anon, authenticated;
GRANT ALL ON public.provinces TO service_role;
GRANT ALL ON public.cities TO service_role;

DO $$
DECLARE
  prov_0_id UUID;
  prov_1_id UUID;
  prov_2_id UUID;
  prov_3_id UUID;
  prov_4_id UUID;
  prov_5_id UUID;
  prov_6_id UUID;
  prov_7_id UUID;
BEGIN

  -- Insert Province: Azad Kashmir
  INSERT INTO public.provinces (name) VALUES ('Azad Kashmir') ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name RETURNING id INTO prov_0_id;
  IF prov_0_id IS NULL THEN SELECT id INTO prov_0_id FROM public.provinces WHERE name = 'Azad Kashmir'; END IF;

  -- Insert Cities for Azad Kashmir
  INSERT INTO public.cities (province_id, name, is_serviceable) VALUES 
  (prov_0_id, 'Bhimbar', true),
  (prov_0_id, 'Kotli', true),
  (prov_0_id, 'Kotli District', true),
  (prov_0_id, 'Mirpur District', true),
  (prov_0_id, 'Muzaffarābād', true),
  (prov_0_id, 'New Mirpur', true),
  (prov_0_id, 'Rawala Kot', true)
  ON CONFLICT DO NOTHING;

  -- Insert Province: Balochistan
  INSERT INTO public.provinces (name) VALUES ('Balochistan') ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name RETURNING id INTO prov_1_id;
  IF prov_1_id IS NULL THEN SELECT id INTO prov_1_id FROM public.provinces WHERE name = 'Balochistan'; END IF;

  -- Insert Cities for Balochistan
  INSERT INTO public.cities (province_id, name, is_serviceable) VALUES 
  (prov_1_id, 'Alik Ghund', true),
  (prov_1_id, 'Awārān District', true),
  (prov_1_id, 'Barkhan', true),
  (prov_1_id, 'Bela', true),
  (prov_1_id, 'Bhag', true),
  (prov_1_id, 'Bārkhān District', true),
  (prov_1_id, 'Chaman', true),
  (prov_1_id, 'Chowki Jamali', true),
  (prov_1_id, 'Chāgai District', true),
  (prov_1_id, 'Dadhar', true),
  (prov_1_id, 'Dalbandin', true),
  (prov_1_id, 'Dera Bugti', true),
  (prov_1_id, 'Dera Bugti District', true),
  (prov_1_id, 'Duki', true),
  (prov_1_id, 'Gadani', true),
  (prov_1_id, 'Garhi Khairo', true),
  (prov_1_id, 'Gwadar', true),
  (prov_1_id, 'Harnai', true),
  (prov_1_id, 'Jhal Magsi District', true),
  (prov_1_id, 'Jiwani', true),
  (prov_1_id, 'Jāfarābād District', true),
  (prov_1_id, 'Kalat', true),
  (prov_1_id, 'Kalāt District', true),
  (prov_1_id, 'Khadan Khak', true),
  (prov_1_id, 'Kharan', true),
  (prov_1_id, 'Khuzdar', true),
  (prov_1_id, 'Khuzdār District', true),
  (prov_1_id, 'Khārān District', true),
  (prov_1_id, 'Kohlu', true),
  (prov_1_id, 'Kot Malik Barkhurdar', true),
  (prov_1_id, 'Lasbela District', true),
  (prov_1_id, 'Loralai', true),
  (prov_1_id, 'Loralai District', true),
  (prov_1_id, 'Mach', true),
  (prov_1_id, 'Mastung', true),
  (prov_1_id, 'Mastung District', true),
  (prov_1_id, 'Mehrabpur', true),
  (prov_1_id, 'Mūsa Khel District', true),
  (prov_1_id, 'Nasīrābād District', true),
  (prov_1_id, 'Nushki', true),
  (prov_1_id, 'Ormara', true),
  (prov_1_id, 'Panjgūr District', true),
  (prov_1_id, 'Pasni', true),
  (prov_1_id, 'Pishin', true),
  (prov_1_id, 'Qila Saifullāh District', true),
  (prov_1_id, 'Quetta', true),
  (prov_1_id, 'Quetta District', true),
  (prov_1_id, 'Sibi', true),
  (prov_1_id, 'Sohbatpur', true),
  (prov_1_id, 'Surab', true),
  (prov_1_id, 'Turbat', true),
  (prov_1_id, 'Usta Muhammad', true),
  (prov_1_id, 'Uthal', true),
  (prov_1_id, 'Zhob', true),
  (prov_1_id, 'Zhob District', true),
  (prov_1_id, 'Ziarat', true),
  (prov_1_id, 'Ziārat District', true)
  ON CONFLICT DO NOTHING;

  -- Insert Province: Federally Administered Tribal Areas
  INSERT INTO public.provinces (name) VALUES ('Federally Administered Tribal Areas') ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name RETURNING id INTO prov_2_id;
  IF prov_2_id IS NULL THEN SELECT id INTO prov_2_id FROM public.provinces WHERE name = 'Federally Administered Tribal Areas'; END IF;

  -- Insert Cities for Federally Administered Tribal Areas
  INSERT INTO public.cities (province_id, name, is_serviceable) VALUES 
  (prov_2_id, 'Alizai', true),
  (prov_2_id, 'Gulishah Kach', true),
  (prov_2_id, 'Landi Kotal', true),
  (prov_2_id, 'Miran Shah', true),
  (prov_2_id, 'North Wazīristān Agency', true),
  (prov_2_id, 'Shinpokh', true),
  (prov_2_id, 'South Wazīristān Agency', true),
  (prov_2_id, 'Wana', true)
  ON CONFLICT DO NOTHING;

  -- Insert Province: Gilgit-Baltistan
  INSERT INTO public.provinces (name) VALUES ('Gilgit-Baltistan') ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name RETURNING id INTO prov_3_id;
  IF prov_3_id IS NULL THEN SELECT id INTO prov_3_id FROM public.provinces WHERE name = 'Gilgit-Baltistan'; END IF;

  -- Insert Cities for Gilgit-Baltistan
  INSERT INTO public.cities (province_id, name, is_serviceable) VALUES 
  (prov_3_id, 'Barishal', true),
  (prov_3_id, 'Gilgit', true),
  (prov_3_id, 'Skardu', true)
  ON CONFLICT DO NOTHING;

  -- Insert Province: Islamabad Capital Territory
  INSERT INTO public.provinces (name) VALUES ('Islamabad Capital Territory') ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name RETURNING id INTO prov_4_id;
  IF prov_4_id IS NULL THEN SELECT id INTO prov_4_id FROM public.provinces WHERE name = 'Islamabad Capital Territory'; END IF;

  -- Insert Cities for Islamabad Capital Territory
  INSERT INTO public.cities (province_id, name, is_serviceable) VALUES 
  (prov_4_id, 'Islamabad', true)
  ON CONFLICT DO NOTHING;

  -- Insert Province: Khyber Pakhtunkhwa
  INSERT INTO public.provinces (name) VALUES ('Khyber Pakhtunkhwa') ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name RETURNING id INTO prov_5_id;
  IF prov_5_id IS NULL THEN SELECT id INTO prov_5_id FROM public.provinces WHERE name = 'Khyber Pakhtunkhwa'; END IF;

  -- Insert Cities for Khyber Pakhtunkhwa
  INSERT INTO public.cities (province_id, name, is_serviceable) VALUES 
  (prov_5_id, 'Abbottabad', true),
  (prov_5_id, 'Akora', true),
  (prov_5_id, 'Aman Garh', true),
  (prov_5_id, 'Amirabad', true),
  (prov_5_id, 'Ashanagro Koto', true),
  (prov_5_id, 'Baffa', true),
  (prov_5_id, 'Bannu', true),
  (prov_5_id, 'Bat Khela', true),
  (prov_5_id, 'Battagram', true),
  (prov_5_id, 'Battagram District', true),
  (prov_5_id, 'Buner District', true),
  (prov_5_id, 'Charsadda', true),
  (prov_5_id, 'Cherat Cantonement', true),
  (prov_5_id, 'Chitral', true),
  (prov_5_id, 'Dera Ismail Khan', true),
  (prov_5_id, 'Dera Ismāīl Khān District', true),
  (prov_5_id, 'Doaba', true),
  (prov_5_id, 'Hangu', true),
  (prov_5_id, 'Haripur', true),
  (prov_5_id, 'Havelian', true),
  (prov_5_id, 'Kakad Wari Dir Upper', true),
  (prov_5_id, 'Karak', true),
  (prov_5_id, 'Khalabat', true),
  (prov_5_id, 'Kohat', true),
  (prov_5_id, 'Kulachi', true),
  (prov_5_id, 'Lachi', true),
  (prov_5_id, 'Lakki', true),
  (prov_5_id, 'Mansehra', true),
  (prov_5_id, 'Mardan', true),
  (prov_5_id, 'Mingora', true),
  (prov_5_id, 'Noorabad', true),
  (prov_5_id, 'Nowshera', true),
  (prov_5_id, 'Nowshera Cantonment', true),
  (prov_5_id, 'Pabbi', true),
  (prov_5_id, 'Paharpur', true),
  (prov_5_id, 'Peshawar', true),
  (prov_5_id, 'Risalpur Cantonment', true),
  (prov_5_id, 'Sarai Naurang', true),
  (prov_5_id, 'Shabqadar', true),
  (prov_5_id, 'Shingli Bala', true),
  (prov_5_id, 'Shorkot', true),
  (prov_5_id, 'Swabi', true),
  (prov_5_id, 'Tangi', true),
  (prov_5_id, 'Tank', true),
  (prov_5_id, 'Thal', true),
  (prov_5_id, 'Topi', true),
  (prov_5_id, 'Upper Dir', true),
  (prov_5_id, 'Utmanzai', true),
  (prov_5_id, 'Zaida', true)
  ON CONFLICT DO NOTHING;

  -- Insert Province: Punjab
  INSERT INTO public.provinces (name) VALUES ('Punjab') ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name RETURNING id INTO prov_6_id;
  IF prov_6_id IS NULL THEN SELECT id INTO prov_6_id FROM public.provinces WHERE name = 'Punjab'; END IF;

  -- Insert Cities for Punjab
  INSERT INTO public.cities (province_id, name, is_serviceable) VALUES 
  (prov_6_id, 'Ahmadpur Sial', true),
  (prov_6_id, 'Ahmedpur East', true),
  (prov_6_id, 'Alipur Chatha', true),
  (prov_6_id, 'Arifwala', true),
  (prov_6_id, 'Attock Tehsil', true),
  (prov_6_id, 'Baddomalhi', true),
  (prov_6_id, 'Bahawalnagar', true),
  (prov_6_id, 'Bahawalpur', true),
  (prov_6_id, 'Bakhri Ahmad Khan', true),
  (prov_6_id, 'Basirpur', true),
  (prov_6_id, 'Basti Dosa', true),
  (prov_6_id, 'Begowala', true),
  (prov_6_id, 'Bhakkar', true),
  (prov_6_id, 'Bhalwal', true),
  (prov_6_id, 'Bhawana', true),
  (prov_6_id, 'Bhera', true),
  (prov_6_id, 'Bhopalwala', true),
  (prov_6_id, 'Burewala', true),
  (prov_6_id, 'Chak Azam Saffo', true),
  (prov_6_id, 'Chak Jhumra', true),
  (prov_6_id, 'Chak One Hundred Twenty Nine Left', true),
  (prov_6_id, 'Chak Thirty-one -Eleven Left', true),
  (prov_6_id, 'Chak Two Hundred Forty-Nine TDA', true),
  (prov_6_id, 'Chakwal', true),
  (prov_6_id, 'Chawinda', true),
  (prov_6_id, 'Chichawatni', true),
  (prov_6_id, 'Chiniot', true),
  (prov_6_id, 'Chishtian', true),
  (prov_6_id, 'Choa Saidanshah', true),
  (prov_6_id, 'Chuhar Kana', true),
  (prov_6_id, 'Chunian', true),
  (prov_6_id, 'Daira Din Panah', true),
  (prov_6_id, 'Dajal', true),
  (prov_6_id, 'Dandot RS', true),
  (prov_6_id, 'Darya Khan', true),
  (prov_6_id, 'Daska', true),
  (prov_6_id, 'Daud Khel', true),
  (prov_6_id, 'Daultala', true),
  (prov_6_id, 'Dera Ghazi Khan', true),
  (prov_6_id, 'Dhanot', true),
  (prov_6_id, 'Dhaunkal', true),
  (prov_6_id, 'Dhok Awan', true),
  (prov_6_id, 'Dijkot', true),
  (prov_6_id, 'Dinan Bashnoian Wala', true),
  (prov_6_id, 'Dinga', true),
  (prov_6_id, 'Dipalpur', true),
  (prov_6_id, 'Dullewala', true),
  (prov_6_id, 'Dunga Bunga', true),
  (prov_6_id, 'Dunyapur', true),
  (prov_6_id, 'Eminabad', true),
  (prov_6_id, 'Faisalabad', true),
  (prov_6_id, 'Faqirwali', true),
  (prov_6_id, 'Faruka', true),
  (prov_6_id, 'Fazilpur', true),
  (prov_6_id, 'Ferozewala', true),
  (prov_6_id, 'Fort Abbas', true),
  (prov_6_id, 'Garh Maharaja', true),
  (prov_6_id, 'Gojra', true),
  (prov_6_id, 'Gujar Khan', true),
  (prov_6_id, 'Gujranwala', true),
  (prov_6_id, 'Gujranwala Division', true),
  (prov_6_id, 'Gujrat', true),
  (prov_6_id, 'Hadali', true),
  (prov_6_id, 'Hafizabad', true),
  (prov_6_id, 'Harnoli', true),
  (prov_6_id, 'Harunabad', true),
  (prov_6_id, 'Hasan Abdal', true),
  (prov_6_id, 'Hasilpur', true),
  (prov_6_id, 'Haveli Lakha', true),
  (prov_6_id, 'Hazro', true),
  (prov_6_id, 'Hujra Shah Muqeem', true),
  (prov_6_id, 'Jahanian Shah', true),
  (prov_6_id, 'Jalalpur Jattan', true),
  (prov_6_id, 'Jalalpur Pirwala', true),
  (prov_6_id, 'Jampur', true),
  (prov_6_id, 'Jand', true),
  (prov_6_id, 'Jandiala Sher Khan', true),
  (prov_6_id, 'Jaranwala', true),
  (prov_6_id, 'Jatoi Shimali', true),
  (prov_6_id, 'Jauharabad', true),
  (prov_6_id, 'Jhang', true),
  (prov_6_id, 'Jhang Sadar', true),
  (prov_6_id, 'Jhawarian', true),
  (prov_6_id, 'Jhelum', true),
  (prov_6_id, 'Kabirwala', true),
  (prov_6_id, 'Kahna Nau', true),
  (prov_6_id, 'Kahuta', true),
  (prov_6_id, 'Kalabagh', true),
  (prov_6_id, 'Kalaswala', true),
  (prov_6_id, 'Kaleke Mandi', true),
  (prov_6_id, 'Kallar Kahar', true),
  (prov_6_id, 'Kalur Kot', true),
  (prov_6_id, 'Kamalia', true),
  (prov_6_id, 'Kamar Mushani', true),
  (prov_6_id, 'Kamoke', true),
  (prov_6_id, 'Kamra', true),
  (prov_6_id, 'Kanganpur', true),
  (prov_6_id, 'Karor', true),
  (prov_6_id, 'Kasur', true),
  (prov_6_id, 'Keshupur', true),
  (prov_6_id, 'Khairpur Tamiwali', true),
  (prov_6_id, 'Khandowa', true),
  (prov_6_id, 'Khanewal', true),
  (prov_6_id, 'Khanga Dogran', true),
  (prov_6_id, 'Khangarh', true),
  (prov_6_id, 'Khanpur', true),
  (prov_6_id, 'Kharian', true),
  (prov_6_id, 'Khewra', true),
  (prov_6_id, 'Khurrianwala', true),
  (prov_6_id, 'Khushab', true),
  (prov_6_id, 'Kohror Pakka', true),
  (prov_6_id, 'Kot Addu Tehsil', true),
  (prov_6_id, 'Kot Ghulam Muhammad', true),
  (prov_6_id, 'Kot Mumin', true),
  (prov_6_id, 'Kot Radha Kishan', true),
  (prov_6_id, 'Kot Rajkour', true),
  (prov_6_id, 'Kot Samaba', true),
  (prov_6_id, 'Kot Sultan', true),
  (prov_6_id, 'Kotli Loharan', true),
  (prov_6_id, 'Kundian', true),
  (prov_6_id, 'Kunjah', true),
  (prov_6_id, 'Ladhewala Waraich', true),
  (prov_6_id, 'Lahore', true),
  (prov_6_id, 'Lala Musa', true),
  (prov_6_id, 'Lalian', true),
  (prov_6_id, 'Layyah', true),
  (prov_6_id, 'Layyah District', true),
  (prov_6_id, 'Liliani', true),
  (prov_6_id, 'Lodhran', true),
  (prov_6_id, 'Mailsi', true),
  (prov_6_id, 'Malakwal', true),
  (prov_6_id, 'Malakwal City', true),
  (prov_6_id, 'Mamu Kanjan', true),
  (prov_6_id, 'Mananwala', true),
  (prov_6_id, 'Mandi Bahauddin', true),
  (prov_6_id, 'Mandi Bahauddin District', true),
  (prov_6_id, 'Mangla', true),
  (prov_6_id, 'Mankera', true),
  (prov_6_id, 'Mehmand Chak', true),
  (prov_6_id, 'Mian Channun', true),
  (prov_6_id, 'Mianke Mor', true),
  (prov_6_id, 'Mianwali', true),
  (prov_6_id, 'Minchinabad', true),
  (prov_6_id, 'Mitha Tiwana', true),
  (prov_6_id, 'Moza Shahwala', true),
  (prov_6_id, 'Multan', true),
  (prov_6_id, 'Multan District', true),
  (prov_6_id, 'Muridke', true),
  (prov_6_id, 'Murree', true),
  (prov_6_id, 'Mustafabad', true),
  (prov_6_id, 'Muzaffargarh', true),
  (prov_6_id, 'Nankana Sahib', true),
  (prov_6_id, 'Narang Mandi', true),
  (prov_6_id, 'Narowal', true),
  (prov_6_id, 'Naushahra Virkan', true),
  (prov_6_id, 'Nazir Town', true),
  (prov_6_id, 'Okara', true),
  (prov_6_id, 'Pakki Shagwanwali', true),
  (prov_6_id, 'Pakpattan', true),
  (prov_6_id, 'Pasrur', true),
  (prov_6_id, 'Pattoki', true),
  (prov_6_id, 'Phalia', true),
  (prov_6_id, 'Pind Dadan Khan', true),
  (prov_6_id, 'Pindi Bhattian', true),
  (prov_6_id, 'Pindi Gheb', true),
  (prov_6_id, 'Pir Mahal', true),
  (prov_6_id, 'Qadirpur Ran', true),
  (prov_6_id, 'Qila Didar Singh', true),
  (prov_6_id, 'Rabwah', true),
  (prov_6_id, 'Rahim Yar Khan', true),
  (prov_6_id, 'Rahimyar Khan District', true),
  (prov_6_id, 'Raiwind', true),
  (prov_6_id, 'Raja Jang', true),
  (prov_6_id, 'Rajanpur', true),
  (prov_6_id, 'Rasulnagar', true),
  (prov_6_id, 'Rawalpindi', true),
  (prov_6_id, 'Rawalpindi District', true),
  (prov_6_id, 'Renala Khurd', true),
  (prov_6_id, 'Rojhan', true),
  (prov_6_id, 'Sadiqabad', true),
  (prov_6_id, 'Sahiwal', true),
  (prov_6_id, 'Sambrial', true),
  (prov_6_id, 'Sangla Hill', true),
  (prov_6_id, 'Sanjwal', true),
  (prov_6_id, 'Sarai Alamgir', true),
  (prov_6_id, 'Sarai Sidhu', true),
  (prov_6_id, 'Sargodha', true),
  (prov_6_id, 'Shahkot Tehsil', true),
  (prov_6_id, 'Shahpur', true),
  (prov_6_id, 'Shahr Sultan', true),
  (prov_6_id, 'Shakargarh', true),
  (prov_6_id, 'Sharqpur', true),
  (prov_6_id, 'Sheikhupura', true),
  (prov_6_id, 'Shorkot', true),
  (prov_6_id, 'Shujaabad', true),
  (prov_6_id, 'Sialkot', true),
  (prov_6_id, 'Sillanwali', true),
  (prov_6_id, 'Sodhra', true),
  (prov_6_id, 'Sukheke Mandi', true),
  (prov_6_id, 'Surkhpur', true),
  (prov_6_id, 'Talagang', true),
  (prov_6_id, 'Talamba', true),
  (prov_6_id, 'Tandlianwala', true),
  (prov_6_id, 'Taunsa', true),
  (prov_6_id, 'Toba Tek Singh', true),
  (prov_6_id, 'Umerkot', true),
  (prov_6_id, 'Vihari', true),
  (prov_6_id, 'Wah', true),
  (prov_6_id, 'Warburton', true),
  (prov_6_id, 'Wazirabad', true),
  (prov_6_id, 'West Punjab', true),
  (prov_6_id, 'Yazman', true),
  (prov_6_id, 'Zafarwal', true),
  (prov_6_id, 'Zahir Pir', true)
  ON CONFLICT DO NOTHING;

  -- Insert Province: Sindh
  INSERT INTO public.provinces (name) VALUES ('Sindh') ON CONFLICT (name) DO UPDATE SET name=EXCLUDED.name RETURNING id INTO prov_7_id;
  IF prov_7_id IS NULL THEN SELECT id INTO prov_7_id FROM public.provinces WHERE name = 'Sindh'; END IF;

  -- Insert Cities for Sindh
  INSERT INTO public.cities (province_id, name, is_serviceable) VALUES 
  (prov_7_id, 'Adilpur', true),
  (prov_7_id, 'Badin', true),
  (prov_7_id, 'Bagarji', true),
  (prov_7_id, 'Bandhi', true),
  (prov_7_id, 'Berani', true),
  (prov_7_id, 'Bhan', true),
  (prov_7_id, 'Bhiria', true),
  (prov_7_id, 'Bhit Shah', true),
  (prov_7_id, 'Bozdar Wada', true),
  (prov_7_id, 'Bulri', true),
  (prov_7_id, 'Chak', true),
  (prov_7_id, 'Chamber', true),
  (prov_7_id, 'Chhor', true),
  (prov_7_id, 'Chuhar Jamali', true),
  (prov_7_id, 'Dadu', true),
  (prov_7_id, 'Daromehar', true),
  (prov_7_id, 'Darya Khan Marri', true),
  (prov_7_id, 'Daulatpur', true),
  (prov_7_id, 'Daur', true),
  (prov_7_id, 'Dhoro Naro', true),
  (prov_7_id, 'Digri', true),
  (prov_7_id, 'Diplo', true),
  (prov_7_id, 'Dokri', true),
  (prov_7_id, 'Gambat', true),
  (prov_7_id, 'Garhiyasin', true),
  (prov_7_id, 'Gharo', true),
  (prov_7_id, 'Ghauspur', true),
  (prov_7_id, 'Ghotki', true),
  (prov_7_id, 'Goth Garelo', true),
  (prov_7_id, 'Goth Phulji', true),
  (prov_7_id, 'Goth Radhan', true),
  (prov_7_id, 'Hala', true),
  (prov_7_id, 'Hingorja', true),
  (prov_7_id, 'Hyderabad', true),
  (prov_7_id, 'Islamkot', true),
  (prov_7_id, 'Jacobabad', true),
  (prov_7_id, 'Jamshoro', true),
  (prov_7_id, 'Jati', true),
  (prov_7_id, 'Jhol', true),
  (prov_7_id, 'Johi', true),
  (prov_7_id, 'Jām Sāhib', true),
  (prov_7_id, 'Kadhan', true),
  (prov_7_id, 'Kambar', true),
  (prov_7_id, 'Kandhkot', true),
  (prov_7_id, 'Kandiari', true),
  (prov_7_id, 'Kandiaro', true),
  (prov_7_id, 'Karachi', true),
  (prov_7_id, 'Karaundi', true),
  (prov_7_id, 'Kario Ghanwar', true),
  (prov_7_id, 'Kashmor', true),
  (prov_7_id, 'Keti Bandar', true),
  (prov_7_id, 'Khadro', true),
  (prov_7_id, 'Khairpur', true),
  (prov_7_id, 'Khairpur Mir’s', true),
  (prov_7_id, 'Khairpur Nathan Shah', true),
  (prov_7_id, 'Khanpur Mahar', true),
  (prov_7_id, 'Kot Diji', true),
  (prov_7_id, 'Kotri', true),
  (prov_7_id, 'Kunri', true),
  (prov_7_id, 'Lakhi', true),
  (prov_7_id, 'Larkana', true),
  (prov_7_id, 'Madeji', true),
  (prov_7_id, 'Malir Cantonment', true),
  (prov_7_id, 'Matiari', true),
  (prov_7_id, 'Matli', true),
  (prov_7_id, 'Mehar', true),
  (prov_7_id, 'Miro Khan', true),
  (prov_7_id, 'Mirpur Bhtoro', true),
  (prov_7_id, 'Mirpur Khas', true),
  (prov_7_id, 'Mirpur Mathelo', true),
  (prov_7_id, 'Mirpur Sakro', true),
  (prov_7_id, 'Mirwah Gorchani', true),
  (prov_7_id, 'Mithi', true),
  (prov_7_id, 'Moro', true),
  (prov_7_id, 'Nabisar', true),
  (prov_7_id, 'Nasirabad', true),
  (prov_7_id, 'Naudero', true),
  (prov_7_id, 'Naukot', true),
  (prov_7_id, 'Naushahro Firoz', true),
  (prov_7_id, 'Nawabshah', true),
  (prov_7_id, 'New Bādāh', true),
  (prov_7_id, 'Pad Idan', true),
  (prov_7_id, 'Pano Aqil', true),
  (prov_7_id, 'Pir Jo Goth', true),
  (prov_7_id, 'Pithoro', true),
  (prov_7_id, 'Rajo Khanani', true),
  (prov_7_id, 'Ranipur', true),
  (prov_7_id, 'Ratodero', true),
  (prov_7_id, 'Rohri', true),
  (prov_7_id, 'Rustam', true),
  (prov_7_id, 'Sakrand', true),
  (prov_7_id, 'Samaro', true),
  (prov_7_id, 'Sanghar', true),
  (prov_7_id, 'Sann', true),
  (prov_7_id, 'Sehwan', true),
  (prov_7_id, 'Setharja Old', true),
  (prov_7_id, 'Shahdad Kot', true),
  (prov_7_id, 'Shahdadpur', true),
  (prov_7_id, 'Shahpur Chakar', true),
  (prov_7_id, 'Shikarpur', true),
  (prov_7_id, 'Sinjhoro', true),
  (prov_7_id, 'Sobhodero', true),
  (prov_7_id, 'Sukkur', true),
  (prov_7_id, 'Sīta Road', true),
  (prov_7_id, 'Talhar', true),
  (prov_7_id, 'Tando Adam', true),
  (prov_7_id, 'Tando Allahyar', true),
  (prov_7_id, 'Tando Bago', true),
  (prov_7_id, 'Tando Jam', true),
  (prov_7_id, 'Tando Mitha Khan', true),
  (prov_7_id, 'Tando Muhammad Khan', true),
  (prov_7_id, 'Tangwani', true),
  (prov_7_id, 'Tharu Shah', true),
  (prov_7_id, 'Thatta', true),
  (prov_7_id, 'Thul', true),
  (prov_7_id, 'Ubauro', true),
  (prov_7_id, 'Umarkot', true),
  (prov_7_id, 'Umerkot District', true),
  (prov_7_id, 'Warah', true)
  ON CONFLICT DO NOTHING;

END $$;
